
version: 2

models:
    - name: trusted_employee
      description: "A trusted employee model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: error
    - name: trusted_customers
      description: "A trusted customers model"
      columns:
          - name: email_id
            description: "The primary key for this table"
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: error
    - name: trusted_orders
      description: "A trusted orders model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - severity: warn
                - not_null
                - severity: error
    - name: trusted_payment
      description: "A trusted_payment model"
      columns:
          - name: payment_id
            description: "The primary key for this table"
            tests:
                - unique
                - severity: warn
                - not_null
                - severity: error