version: 2

models:
  - name: trusted_customers
    description: "trusted Layer"
    columns:
     - name: id
       tests:
         - not_null:
            config:
              severity: warn